version: "3.8"

services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    ports:
      - "5000:5000"
    volumes:
      - ./octoprint_data:/octoprint
    restart: unless-stopped
    environment:
      - ENABLE_MJPG_STREAMER=false

  node-red:
    container_name: node-red
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    image: nodered/node-red:latest
    user: "0:1000"
    restart: unless-stopped
    volumes:
      - "./node-red:/data"
    ports:
      - "1881:1880"
    networks:
      - octo-red

  mqtt:
    image: eclipse-mosquitto:1.6.13
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      - octo-red


  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - octo-red
  #   restart: unless-stopped

networks:
  octo-red:
    driver: bridge

volumes:
  octoprint_data:
