version: "3.8"

services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./docker_containers/octoprint_data:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=false
    networks:
      - octo-red

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    user: "0:1000"
    restart: unless-stopped
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    volumes:
      - "./docker_containers/node-red:/data"
    ports:
      - "1881:1880"
    networks:
      - octo-red

  mqtt:
    image: eclipse-mosquitto:1.6.13
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      - octo-red

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - octo-red

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - octo-red

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - octo-red

networks:
  octo-red:
    driver: bridge

volumes:
  octoprint_data:
  mongodb_data: